name: DailyTrendScrape
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install scraper
        run: |
          npm install -g tiktok-scraper
      - name: Run Trending Scraper Script
        run: |
          bash ./scripts/scraper.sh
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Daily Trend Scrape
          file_pattern: "**/*.csv"
          repository: .
