name: WeeklyTrendUpload
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install scraper
        run: |
          npm install -g tiktok-scraper
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Download Videos
        run: |
          mkdir -pv ./videos
          python ./scripts/weekly_processing.py --week data/$(date +week%U)
      - name: Setup FFMpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
      - name: Convert Videos to Landscape
        run: |
          mkdir -pv ./adjusted_videos
          find . -type f -name "./videos/*.mp4" -exec bash v2hconvert.sh {} ./adjusted_videos \;
      - name: Concat Videos
        run: |
          bash ./scripts/concatvideos.sh ./adjusted_videos
      - name: Save Videos
        uses: actions/upload-artifact@v2
        with:
          name: final-video
          path: ./adjusted_videos/output.mp4